version: 2

updates:
  # frontend (Next / npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"

  # backend (uv)
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"

  # frontend container
  - package-ecosystem: "docker"
    directory: "/frontend/.devcontainer"
    schedule:
      interval: "daily"

  # backend container
  - package-ecosystem: "docker"
    directory: "/backend/.devcontainer"
    schedule:
      interval: "daily"
