version: 2

updates:
  # frontend (Next / npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"

  # backend (uv)
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"
