makemigrations inventory:
	python manage.py makemigrations inventory --settings config.settings.development

migrate:
	python manage.py migrate --settings config.settings.development

runserver:
	python manage.py runserver --settings config.settings.development

shell:
	python manage.py shell --settings config.settings.development

startapp:
	django-admin startapp
