# https://biomejs.dev/ja/recipes/continuous-integration/
name: Biome Check

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Get Biome version
        id: biome_version
        run: |
          VERSION=$(biome --version | awk '{print $NF}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get schema version
        id: schema_version
        run: |
          SCHEMA=$(jq -r '."$schema"' frontend/biome.json | sed 's#.*/##; s#/schema.json##')
          echo "version=$SCHEMA" >> $GITHUB_OUTPUT

      - name: Run Biome migrate if needed
        if: |
          github.actor == 'dependabot[bot]' &&
          steps.biome_version.outputs.version != steps.schema_version.outputs.version
        run: biome migrate --write
        working-directory: frontend

      - name: Commit biome changes
        if: |
          github.actor == 'dependabot[bot]' &&
          steps.biome_version.outputs.version != steps.schema_version.outputs.version
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add frontend/biome.json
            git commit -m "chore: biome migrate [skip ci]"

            BRANCH="${{ github.head_ref }}"

            git fetch origin $BRANCH
            git rebase origin/$BRANCH

            git push --force-with-lease origin HEAD:$BRANCH
          fi

      - name: Run Biome
        run: biome ci .
        working-directory: frontend
